### ISSUE TITLE
Implement all Buttons in (intent) modal

### ISSUE THREAD

**Issue by viktorsmari** [reflow-project/weloop#41]
Related: #19 

Prioritize:

- [x] Make a Request
- [x] Transfer action
- [x] History
- [ ] Remaining
- [ ] Comment #39 
- [ ] Follow #40 
- [x] Actions dropdown (not fully implemented #34)

How to trigger this modal?
1. Go to any **community** and click **Intents** tab
2. Click any resource

![2021-05-10_12-07-20](https://user-images.githubusercontent.com/1689020/117943962-f9fcb600-b30c-11eb-9ef5-e11d25eb54f9.png)

**Comment by kariyngva** [comment]
I'm not seeing a clear way of following an Intent. See `follow`query and result.

```graphql
mutation {
  createFollow(contextId: "01F1XC0XJHM6EK66C7F6DF4K6H") {
    canonicalUrl
    id
  }
}
```

```json
{
  "data": {
    "createFollow": null
  }
}
```

I figured since the follow didn't work as I thought. The comment (thread) might be enough.
That is, creating a follow or a comment would create a thread attached to the intent which could be followed. This would of course mean that users never really followed the Intent but a thread attached to it.

I create a thread with a comment, like so:

```graphql
mutation {
  createThread(contextId: "01F1XC0XJHM6EK66C7F6DF4K6H", comment:{content: "Some comment"}) {
    canonicalUrl
    id
  }
}
```

The problem however is **a)** `createThread` returns the `Comment`

```json
{
  "data": {
    "createThread": {
      "canonicalUrl": "http://api.reflowproject.eu/pub/objects/01F44C3QF3B1PDWJSBXADGJ2R2",
      "id": "01F44C3QF3D8P00EBBT7JE4VYE"
    }
  }
}
```

So in order to get the thread id we need the following queries:

```graphql
  comment(commentId: "01F44C3QF3D8P00EBBT7JE4VYE") {
    thread {
      id
    }
  }
```
take the id from the result:
```json
  "data": {
    "comment": {
      "thread": {
        "id": "01F44C3QEZ82XJ1EAVZV9QVRAP"
      }
    }
  }
```

And then we can query for the thread:
```graphql
  thread(threadId: "01F44C3QEZ82XJ1EAVZV9QVRAP") {
    comments {
      edges {
        content
      }
    }
  }
```

And get the comment.

```json
"thread": {
      "comments": {
        "edges": [
          {
            "content": "Some comment"
          }
        ]
      }
    }
```

This however does not solve **b)** the issue of getting the thread id from the intent. I'm not seeing anything in the docs or the graphql schema explorer that allows either getting comments or threads attached to an intent.
